name: fibonacci
description: Fibonacci Mindset

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  alarm: ^3.0.10

  app_settings: 4.2.0
  ####### ####### #######



  ####### ####### #######
  back_button_interceptor: ^7.0.0

  blur: ^3.0.0
  ####### ####### #######



  ####### ####### #######
  connectivity_plus: ^3.0.3

  cloud_firestore: ^4.0.5
  cloud_functions: ^4.0.4

  cupertino_icons: ^1.0.5
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^2.2.0

  firebase_analytics: ^10.0.5
  firebase_crashlytics: ^3.0.5

  firebase_auth: ^4.1.2

  firebase_database: ^10.2.7

  firebase_remote_config: ^3.0.5
  firebase_messaging: ^14.1.0
  firebase_in_app_messaging: ^0.7.0+5

  firebase_dynamic_links: ^5.0.5

  flutter_phoenix: ^1.0.0
  ####### ####### #######



  ####### ####### #######
  google_sign_in: ^6.0.1

  gradient_borders: ^1.0.0
  ####### ####### #######



  ####### ####### #######
  in_app_purchase: ^3.1.10
  ####### ####### #######



  ####### ####### #######
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  local_auth: ^2.1.0
  ####### ####### #######



  ####### ####### #######
  marquee: ^2.2.3
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^1.0.6
  ####### ####### #######



  ####### ####### #######
  share_plus: ^7.2.2

  shared_preferences: ^2.0.15

  sleek_circular_slider: ^2.0.1
  status_bar_control: ^3.2.1
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######



  ####### ####### #######
  widget_mask: ^1.0.0+0
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/



  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Modern
      fonts:
        - asset: fonts/anurati.otf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf